openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /{rpath}:
    get:
      operationId: doRedirect
      parameters:
        - name: rpath
          in: path
          required: true
      x-vertx-event-bus: simple.service
      responses:
        '302':
          description: 'redirect by 302 status'
